trigger: 
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: 'self-hosted'
    steps:
    - script: echo "The agent is alive!"
      displayName: 'Sanity Check'
      
    - checkout: self

    - task: Npm@1
      inputs:
        command: 'install'

    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'

    - script: ls -la $(Build.SourcesDirectory)/build
      displayName: 'Verify build folder contents'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/build'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'

#-------------------------------------------------------------------------------------

# - stage: Deploy
#   dependsOn: Build
#   jobs:
#   - job: Deploy
#     pool:
#       name: 'self-hosted'
#     steps:
#       - download: none

#       - task: DownloadBuildArtifacts@1
#         inputs:
#           buildType: 'current'
#           downloadType: 'single'
#           artifactName: 'drop'
#           downloadPath: '$(System.ArtifactsDirectory)'

#       - task: AzureRmWebAppDeployment@5
#         inputs:
#           ConnectionType: 'AzureRM'
#           azureSubscription: 'Azure subscription 1(281d6df1-9dfc-46bb-a0e9-46971c2d4d33)'
#           appType: 'webAppLinux'
#           WebAppName: 'simple-project'
#           packageForLinux: '$(System.ArtifactsDirectory)/drop/app.zip'
#           RuntimeStack: 'NODE|22-lts'
#           DeploymentTypeLinux: 'oneDeploy'
#           StartupCommand: 'npm install && node server.js'
